apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
  labels:
    app: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: middleware
        image: tilt-middleware
        ports:
        - containerPort: 4000
