name: VSF Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - ci/pre-release-no-hardcoded-env

jobs:
  release-packages:
    name: "Release NPM Packages"
    uses: ./.github/workflows/cd-integrations.yml
    secrets: inherit
    with:
      enterprise: false
