name: VSF Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/ust-1534-global-state-manager

jobs:
  release-packages:
    name: "Release NPM Packages"
    uses: ./.github/workflows/cd-integrations.yml
    secrets: inherit
    with:
      enterprise: false
