name: VSF Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - CLOUD-3497-add-terminus
      
jobs:
  release-packages:
    name: "Release NPM Packages"
    uses: ./.github/workflows/cd-integrations.yml
    secrets: inherit
    with:
      enterprise: false
