name: CI
on: 
  pull_request:
    branches:
      - next
      - release/next
jobs:
  lhci:
    name: Lighthouse CI Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --network-concurrency 1 --frozen-lockfile

      - name: Build
        run: yarn build:ct

      - name: run Lighthouse CI mobile
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: run Lighthouse CI desktop
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun --collect.settings.preset=desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}