name: Lint, build, test

on:
  push:
    branches:
      - main
      - develop
      - release-**
  pull_request:
    branches:
      - main
      - develop
      - release-**

jobs:
  test_repository:
    name: Run linter, build and test all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
              
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
